

def LoadPNGImage(path: str) -> "nk_image": ...

def LoadSVGImage(path: str, w: int, h: int) -> "nk_image": ...

def TransformImage(image: "nk_image", w: int, h: int, crop: "nk_rect") -> "nk_image": ...

class Window:
    def __init__(self) -> None: ...

    def GLFWInit(self) -> None: ...

    def CreateWindow(self, w: int, h: int, title: str, decorated: bool, LayerShell: bool) -> None: ...

    def GetNKContext(self) -> "nk_context": ...

    def NewFrame(self) -> None: ...

    def Render(self) -> None: ...

    def PollEvents(self) -> None: ...

    def WaitEvents(self) -> None: ...

    def ShouldClose(self) -> bool: ...

    def SetShouldClose(self, arg: bool, /) -> None: ...

    def GetWindowSize(self) -> tuple[int, int]: ...

    def LS_SetExclusiveZone(self, zone: int) -> None: ...

    def LS_SetMargin(self, top: int, right: int, bottom: int, left: int) -> None: ...

    def LS_SetLayer(self, layer: int) -> None:
        """0--TOP, 1--OVERLAY, 2--BOTTOM, 3--BACKGROUND"""

    def LS_SetAnchor(self, achor: int) -> None:
        """0--TOP, 1--BOTTOM, 2--LEFT, 3--RIGHT"""

    def SetKeyboardFocus(self, focus: bool) -> None: ...

    def Shutdown(self) -> None: ...

    def InitFont(self, customFont: bool, path: str, bold: int) -> None: ...
